### ISSUE TITLE
Wiring Schematics

### ISSUE THREAD

**Issue by double-fault** [schreibfaul1/ESP32-TFT-Library-ILI9486#3]
I've got a 3.5" RPi LCD (A), which I believe I can use with my Arduino Uno using this library. Could I please know the wiring schematics for the example in this repository? Which pin on the display should I connect to which pin on the Arduino Uno?

**Comment by schreibfaul1** [comment]
I think a Arduino Uno is to slow and has not enough flash to save the fonts. So I can't say it will work. The wires are MISIO to MISO, SCK to SCK, MOSI to MOSI.
TFT_CS, TP_CS, TFT_DC and TP_IRQ can connected to any available digital ports.
