### ISSUE TITLE
3.5" TFT LCD with strange pin out

### ISSUE THREAD

**Issue by Jordise2002** [schreibfaul1/ESP32-TFT-Library-ILI9486#7]
Hi I bought this tft out of amazon.
I think it was designed for the arduino mega but I was wondering if I could use it with an esp32. However, I can't understand how to connect it to the microprocesor. Could anyone help me?
![WhatsApp Image 2021-03-08 at 22 13 16](https://user-images.githubusercontent.com/80289256/110382725-98de0b00-805b-11eb-803f-ed228b588bbb.jpeg)

**Comment by katurov** [comment]
Just take arduino pin-out and use it's map to understand where is power, SPI and so on. I hope this will be easy

**Comment by optimaxch** [comment]
Jordi,

.................
// Digital I/O used
//------SPI----------------
#define SD_CS          5
#define SPI_MOSI      23
#define SPI_MISO      19
#define SPI_SCK       18
//------I2S audio----------
#define I2S_DOUT      25
#define I2S_BCLK      26
#define I2S_LRC       32
//------TFT-----------------
#define TFT_CS        15
#define TFT_DC         9


TFT tft;
WiFiMulti wifiMulti;
String ssid =     "2.4GHz";
String password = "2020!Dr3221";
.......................
exactly like schreibfaul code, 
and put 3V to LED_BKL

  opti
