### ISSUE TITLE
request for scematic of tft module 

### ISSUE THREAD

**Issue by clear-sky** [schreibfaul1/ESP32-TFT-Library-ILI9486#9]
hi dear  schreibfaul1 
thanks for your work!
i have ili9486 (parallel mode) bare lcd and want to make a spi to parallel converter for my lcd
this is mu lcd:
http://aitendo3.sakura.ne.jp/aitendo_data/product_img/lcd/tft2/Z350IT002/Z350IT002_aitendo.pdf
do you have any schematic or info from RPi LCD (A) or RPi LCD (B)?

**Comment by schreibfaul1** [comment]
https://github.com/schreibfaul1/ESP32-TFT-Library-ILI9486/blob/master/images/SPI%20DIsplay.JPG
This is the circuit of LCD(A)

**Comment by clear-sky** [comment]
thank you for answer
you are very kind!
